// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// VCS coverage exclude_file
module ram_2x361(	// src/main/scala/chisel3/util/Queue.scala:73:91
  input          R0_addr,
                 R0_en,
                 R0_clk,
  output [360:0] R0_data,
  input          W0_addr,
                 W0_en,
                 W0_clk,
  input  [360:0] W0_data
);

  reg [360:0] Memory[0:1];	// src/main/scala/chisel3/util/Queue.scala:73:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Queue.scala:73:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Queue.scala:73:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Queue.scala:73:91
    reg [383:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Queue.scala:73:91
    initial begin	// src/main/scala/chisel3/util/Queue.scala:73:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:73:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Queue.scala:73:91
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          for (logic [8:0] j = 9'h0; j < 9'h180; j += 9'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:73:91
          end
          Memory[i[0]] = _RANDOM_MEM[360:0];	// src/main/scala/chisel3/util/Queue.scala:73:91
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 361'bx;	// src/main/scala/chisel3/util/Queue.scala:73:91
endmodule

module Queue2_AChannelWithSpare(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input          clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                 reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output         io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [2:0]   io_enq_bits_a_opcode,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_a_param,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0]   io_enq_bits_a_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [5:0]   io_enq_bits_a_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [31:0]  io_enq_bits_a_address,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_a_mask,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [255:0] io_enq_bits_a_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0]   io_enq_bits_a_user_rsvd,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [3:0]   io_enq_bits_a_user_instr_type,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [6:0]   io_enq_bits_a_user_cmd_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_a_user_data_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_bits_spare,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [2:0]   io_deq_bits_a_opcode,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_a_param,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0]   io_deq_bits_a_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [5:0]   io_deq_bits_a_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [31:0]  io_deq_bits_a_address,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_a_mask,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [255:0] io_deq_bits_a_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0]   io_deq_bits_a_user_rsvd,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [3:0]   io_deq_bits_a_user_instr_type,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [6:0]   io_deq_bits_a_user_cmd_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_a_user_data_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_bits_spare	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  wire [360:0] _ram_ext_R0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg          wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire         ptr_match = wrap == wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:77:33
  wire         empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :78:{25,28}
  wire         full = ptr_match & maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :79:24
  wire         io_deq_valid_0 = io_enq_valid | ~empty;	// src/main/scala/chisel3/util/Queue.scala:78:25, :102:{16,19}, :114:{24,39}
  wire         do_deq = ~empty & io_deq_ready & io_deq_valid_0;	// src/main/scala/chisel3/util/Queue.scala:78:25, :81:27, :102:16, :114:{24,39}, :115:17, :117:14, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         do_enq = ~(empty & io_deq_ready) & ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:78:25, :79:24, :80:27, :103:19, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      wrap <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      wrap_1 <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    end
    else begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      if (do_enq)	// src/main/scala/chisel3/util/Queue.scala:80:27, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap <= wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/Queue.scala:81:27, :115:17, :117:14, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap_1 <= wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Queue.scala:76:27, :80:27, :81:27, :93:{15,27}, :94:16, :115:17, :117:14, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, :80:27, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x361 ram_ext (	// src/main/scala/chisel3/util/Queue.scala:73:91
    .R0_addr (wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Queue.scala:80:27, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_a_opcode,
        io_enq_bits_a_param,
        io_enq_bits_a_size,
        io_enq_bits_a_source,
        io_enq_bits_a_address,
        io_enq_bits_a_mask,
        io_enq_bits_a_data,
        io_enq_bits_a_user_rsvd,
        io_enq_bits_a_user_instr_type,
        io_enq_bits_a_user_cmd_intg,
        io_enq_bits_a_user_data_intg,
        io_enq_bits_spare})	// src/main/scala/chisel3/util/Queue.scala:73:91
  );	// src/main/scala/chisel3/util/Queue.scala:73:91
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :103:19
  assign io_deq_valid = io_deq_valid_0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :102:16, :114:{24,39}
  assign io_deq_bits_a_opcode = empty ? io_enq_bits_a_opcode : _ram_ext_R0_data[360:358];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_param = empty ? io_enq_bits_a_param : _ram_ext_R0_data[357:355];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_size = empty ? io_enq_bits_a_size : _ram_ext_R0_data[354:350];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_source = empty ? io_enq_bits_a_source : _ram_ext_R0_data[349:344];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_address =
    empty ? io_enq_bits_a_address : _ram_ext_R0_data[343:312];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_mask = empty ? io_enq_bits_a_mask : _ram_ext_R0_data[311:280];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_data = empty ? io_enq_bits_a_data : _ram_ext_R0_data[279:24];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_user_rsvd =
    empty ? io_enq_bits_a_user_rsvd : _ram_ext_R0_data[23:19];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_user_instr_type =
    empty ? io_enq_bits_a_user_instr_type : _ram_ext_R0_data[18:15];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_user_cmd_intg =
    empty ? io_enq_bits_a_user_cmd_intg : _ram_ext_R0_data[14:8];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_a_user_data_intg =
    empty ? io_enq_bits_a_user_data_intg : _ram_ext_R0_data[7:1];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_spare = empty ? io_enq_bits_spare : _ram_ext_R0_data[0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
endmodule

// VCS coverage exclude_file
module ram_2x290(	// src/main/scala/chisel3/util/Queue.scala:73:91
  input          R0_addr,
                 R0_en,
                 R0_clk,
  output [289:0] R0_data,
  input          W0_addr,
                 W0_en,
                 W0_clk,
  input  [289:0] W0_data
);

  reg [289:0] Memory[0:1];	// src/main/scala/chisel3/util/Queue.scala:73:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Queue.scala:73:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Queue.scala:73:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Queue.scala:73:91
    reg [319:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Queue.scala:73:91
    initial begin	// src/main/scala/chisel3/util/Queue.scala:73:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:73:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Queue.scala:73:91
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          for (logic [8:0] j = 9'h0; j < 9'h140; j += 9'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:73:91
          end
          Memory[i[0]] = _RANDOM_MEM[289:0];	// src/main/scala/chisel3/util/Queue.scala:73:91
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 290'bx;	// src/main/scala/chisel3/util/Queue.scala:73:91
endmodule

module Queue2_DChannelWithSpare(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input          clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                 reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output         io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [2:0]   io_enq_bits_d_opcode,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_d_param,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0]   io_enq_bits_d_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [5:0]   io_enq_bits_d_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_bits_d_sink,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [255:0] io_enq_bits_d_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [6:0]   io_enq_bits_d_user_rsp_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_d_user_data_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_bits_d_error,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_enq_bits_spare,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [2:0]   io_deq_bits_d_opcode,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_d_param,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0]   io_deq_bits_d_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [5:0]   io_deq_bits_d_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_bits_d_sink,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [255:0] io_deq_bits_d_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [6:0]   io_deq_bits_d_user_rsp_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_d_user_data_intg,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_bits_d_error,	// src/main/scala/chisel3/util/Queue.scala:72:14
                 io_deq_bits_spare	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  wire [289:0] _ram_ext_R0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg          wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire         ptr_match = wrap == wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:77:33
  wire         empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :78:{25,28}
  wire         full = ptr_match & maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :79:24
  wire         io_deq_valid_0 = io_enq_valid | ~empty;	// src/main/scala/chisel3/util/Queue.scala:78:25, :102:{16,19}, :114:{24,39}
  wire         do_deq = ~empty & io_deq_ready & io_deq_valid_0;	// src/main/scala/chisel3/util/Queue.scala:78:25, :81:27, :102:16, :114:{24,39}, :115:17, :117:14, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         do_enq = ~(empty & io_deq_ready) & ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:78:25, :79:24, :80:27, :103:19, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      wrap <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      wrap_1 <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    end
    else begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      if (do_enq)	// src/main/scala/chisel3/util/Queue.scala:80:27, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap <= wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/Queue.scala:81:27, :115:17, :117:14, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap_1 <= wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Queue.scala:76:27, :80:27, :81:27, :93:{15,27}, :94:16, :115:17, :117:14, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, :80:27, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x290 ram_ext (	// src/main/scala/chisel3/util/Queue.scala:73:91
    .R0_addr (wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Queue.scala:80:27, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_d_opcode,
        io_enq_bits_d_param,
        io_enq_bits_d_size,
        io_enq_bits_d_source,
        io_enq_bits_d_sink,
        io_enq_bits_d_data,
        io_enq_bits_d_user_rsp_intg,
        io_enq_bits_d_user_data_intg,
        io_enq_bits_d_error,
        io_enq_bits_spare})	// src/main/scala/chisel3/util/Queue.scala:73:91
  );	// src/main/scala/chisel3/util/Queue.scala:73:91
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :103:19
  assign io_deq_valid = io_deq_valid_0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :102:16, :114:{24,39}
  assign io_deq_bits_d_opcode = empty ? io_enq_bits_d_opcode : _ram_ext_R0_data[289:287];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_d_param = empty ? io_enq_bits_d_param : _ram_ext_R0_data[286:284];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_d_size = empty ? io_enq_bits_d_size : _ram_ext_R0_data[283:279];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_d_source = empty ? io_enq_bits_d_source : _ram_ext_R0_data[278:273];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_d_sink = empty ? io_enq_bits_d_sink : _ram_ext_R0_data[272];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_d_data = empty ? io_enq_bits_d_data : _ram_ext_R0_data[271:16];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_d_user_rsp_intg =
    empty ? io_enq_bits_d_user_rsp_intg : _ram_ext_R0_data[15:9];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_d_user_data_intg =
    empty ? io_enq_bits_d_user_data_intg : _ram_ext_R0_data[8:2];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_d_error = empty ? io_enq_bits_d_error : _ram_ext_R0_data[1];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
  assign io_deq_bits_spare = empty ? io_enq_bits_spare : _ram_ext_R0_data[0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :78:25, :110:17, :115:17, :116:19
endmodule

module TlulFifoSync(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:6:7
  input          clock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:6:7
                 reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:6:7
  output         io_host_a_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input          io_host_a_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [2:0]   io_host_a_bits_opcode,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_host_a_bits_param,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [4:0]   io_host_a_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [5:0]   io_host_a_bits_source,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [31:0]  io_host_a_bits_address,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_host_a_bits_mask,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [255:0] io_host_a_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [4:0]   io_host_a_bits_user_rsvd,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [3:0]   io_host_a_bits_user_instr_type,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [6:0]   io_host_a_bits_user_cmd_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_host_a_bits_user_data_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input          io_host_d_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output         io_host_d_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [2:0]   io_host_d_bits_opcode,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_host_d_bits_param,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [4:0]   io_host_d_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [5:0]   io_host_d_bits_source,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output         io_host_d_bits_sink,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [255:0] io_host_d_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [6:0]   io_host_d_bits_user_rsp_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_host_d_bits_user_data_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output         io_host_d_bits_error,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input          io_device_a_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output         io_device_a_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [2:0]   io_device_a_bits_opcode,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_device_a_bits_param,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [4:0]   io_device_a_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [5:0]   io_device_a_bits_source,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [31:0]  io_device_a_bits_address,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_device_a_bits_mask,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [255:0] io_device_a_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [4:0]   io_device_a_bits_user_rsvd,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [3:0]   io_device_a_bits_user_instr_type,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output [6:0]   io_device_a_bits_user_cmd_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_device_a_bits_user_data_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output         io_device_d_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input          io_device_d_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [2:0]   io_device_d_bits_opcode,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_device_d_bits_param,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [4:0]   io_device_d_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [5:0]   io_device_d_bits_source,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input          io_device_d_bits_sink,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [255:0] io_device_d_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input  [6:0]   io_device_d_bits_user_rsp_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_device_d_bits_user_data_intg,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input          io_device_d_bits_error,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
                 io_spare_req_i,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output         io_spare_req_o,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  input          io_spare_rsp_i,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
  output         io_spare_rsp_o	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:20:14
);

  Queue2_AChannelWithSpare reqFifo (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:48:25
    .clock                         (clock),
    .reset                         (reset),
    .io_enq_ready                  (io_host_a_ready),
    .io_enq_valid                  (io_host_a_valid),
    .io_enq_bits_a_opcode          (io_host_a_bits_opcode),
    .io_enq_bits_a_param           (io_host_a_bits_param),
    .io_enq_bits_a_size            (io_host_a_bits_size),
    .io_enq_bits_a_source          (io_host_a_bits_source),
    .io_enq_bits_a_address         (io_host_a_bits_address),
    .io_enq_bits_a_mask            (io_host_a_bits_mask),
    .io_enq_bits_a_data            (io_host_a_bits_data),
    .io_enq_bits_a_user_rsvd       (io_host_a_bits_user_rsvd),
    .io_enq_bits_a_user_instr_type (io_host_a_bits_user_instr_type),
    .io_enq_bits_a_user_cmd_intg   (io_host_a_bits_user_cmd_intg),
    .io_enq_bits_a_user_data_intg  (io_host_a_bits_user_data_intg),
    .io_enq_bits_spare             (io_spare_req_i),
    .io_deq_ready                  (io_device_a_ready),
    .io_deq_valid                  (io_device_a_valid),
    .io_deq_bits_a_opcode          (io_device_a_bits_opcode),
    .io_deq_bits_a_param           (io_device_a_bits_param),
    .io_deq_bits_a_size            (io_device_a_bits_size),
    .io_deq_bits_a_source          (io_device_a_bits_source),
    .io_deq_bits_a_address         (io_device_a_bits_address),
    .io_deq_bits_a_mask            (io_device_a_bits_mask),
    .io_deq_bits_a_data            (io_device_a_bits_data),
    .io_deq_bits_a_user_rsvd       (io_device_a_bits_user_rsvd),
    .io_deq_bits_a_user_instr_type (io_device_a_bits_user_instr_type),
    .io_deq_bits_a_user_cmd_intg   (io_device_a_bits_user_cmd_intg),
    .io_deq_bits_a_user_data_intg  (io_device_a_bits_user_data_intg),
    .io_deq_bits_spare             (io_spare_req_o)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:48:25
  Queue2_DChannelWithSpare rspFifo (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:76:13
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (io_device_d_ready),
    .io_enq_valid                 (io_device_d_valid),
    .io_enq_bits_d_opcode         (io_device_d_bits_opcode),
    .io_enq_bits_d_param          (io_device_d_bits_param),
    .io_enq_bits_d_size           (io_device_d_bits_size),
    .io_enq_bits_d_source         (io_device_d_bits_source),
    .io_enq_bits_d_sink           (io_device_d_bits_sink),
    .io_enq_bits_d_data
      (io_device_d_bits_opcode == 3'h1 ? io_device_d_bits_data : 256'h0),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:68:38, :69:29
    .io_enq_bits_d_user_rsp_intg  (io_device_d_bits_user_rsp_intg),
    .io_enq_bits_d_user_data_intg (io_device_d_bits_user_data_intg),
    .io_enq_bits_d_error          (io_device_d_bits_error),
    .io_enq_bits_spare            (io_spare_rsp_i),
    .io_deq_ready                 (io_host_d_ready),
    .io_deq_valid                 (io_host_d_valid),
    .io_deq_bits_d_opcode         (io_host_d_bits_opcode),
    .io_deq_bits_d_param          (io_host_d_bits_param),
    .io_deq_bits_d_size           (io_host_d_bits_size),
    .io_deq_bits_d_source         (io_host_d_bits_source),
    .io_deq_bits_d_sink           (io_host_d_bits_sink),
    .io_deq_bits_d_data           (io_host_d_bits_data),
    .io_deq_bits_d_user_rsp_intg  (io_host_d_bits_user_rsp_intg),
    .io_deq_bits_d_user_data_intg (io_host_d_bits_user_data_intg),
    .io_deq_bits_d_error          (io_host_d_bits_error),
    .io_deq_bits_spare            (io_spare_rsp_o)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/TlulFifoSync.scala:76:13
endmodule


// ----- 8< ----- FILE "verification/cover/layers-TlulFifoSync-Verification_Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_TlulFifoSync_Verification_Cover
`define layers_TlulFifoSync_Verification_Cover	// <stdin>:22:5
`endif // layers_TlulFifoSync_Verification_Cover	// <stdin>:22:5

// ----- 8< ----- FILE "verification/assume/layers-TlulFifoSync-Verification_Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_TlulFifoSync_Verification_Assume
`define layers_TlulFifoSync_Verification_Assume	// <stdin>:21:5
`endif // layers_TlulFifoSync_Verification_Assume	// <stdin>:21:5

// ----- 8< ----- FILE "verification/assert/layers-TlulFifoSync-Verification_Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_TlulFifoSync_Verification_Assert
`define layers_TlulFifoSync_Verification_Assert	// <stdin>:20:5
`endif // layers_TlulFifoSync_Verification_Assert	// <stdin>:20:5
